/*
 * This source file was generated by the Gradle 'init' task
 */
package com.musec.client;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertNotNull;

class AppTest {
    @Test void appInstantiates() {
        App app = new App();
        assertNotNull(app);
    }
}
