/*
 * This source file was generated by the Gradle 'init' task
 */
package com.musec.client;

import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;

import java.net.URL;

public class App extends Application {

    @Override
    public void start(Stage primaryStage) throws Exception {
        URL fxmlLocation = getClass().getResource("/fxml/MainView.fxml");
        if (fxmlLocation == null) {
            System.err.println("Could not find /fxml/MainView.fxml");
            System.exit(1);
        }
        Parent root = FXMLLoader.load(fxmlLocation);
        
        Scene scene = new Scene(root, 1024, 768);
        
        primaryStage.setTitle("Musec");
        primaryStage.setScene(scene);
        primaryStage.setMinWidth(800);
        primaryStage.setMinHeight(600);
        primaryStage.show();
    }

    public static void main(String[] args) {
        launch(args);
    }
}
